AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for MongoDB-backed API using Lambda and API Gateway with logging"

Parameters:
  MongoDBConnectionString:
    Type: String
    Description: "MongoDB Atlas Connection URI"

  LambdaS3Bucket:
    Type: String
    Description: "S3 Bucket where all Lambda function code is stored"

Resources:

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: LambdaLoggingPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

  # CloudWatch Log Group for Lambda
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AddProductLambda}"
      RetentionInDays: 7

  # Lambda Function for Add Product
  AddProductLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "AddProduct"
      Runtime: python3.8
      Handler: add_product.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: "add_product.zip"
      Environment:
        Variables:
          MONGO_URI: !Ref MongoDBConnectionString
      Timeout: 10

  # Lambda Function for Get Products
  GetProductsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "GetProducts"
      Runtime: python3.8
      Handler: get_products.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: "get_products.zip"
      Environment:
        Variables:
          MONGO_URI: !Ref MongoDBConnectionString
      Timeout: 10

  # API Gateway
  APIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "MongoDBProductAPI"

  # API Gateway CloudWatch Log Group
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/api-gateway/${APIGateway}"
      RetentionInDays: 7

  # API Resource (/products)
  ProductsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGateway
      ParentId: !GetAtt APIGateway.RootResourceId
      PathPart: "products"

  # API Method (POST /products/add)
  AddProductMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref APIGateway
      ResourceId: !Ref ProductsResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AddProductLambda.Arn}/invocations"

  # API Method (GET /products)
  GetProductsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref APIGateway
      ResourceId: !Ref ProductsResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetProductsLambda.Arn}/invocations"

  # Grant API Gateway Permission to invoke AddProduct Lambda
  AddProductLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AddProductLambda
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/*/POST/products"

  # Grant API Gateway Permission to invoke GetProducts Lambda
  GetProductsLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetProductsLambda
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/*/GET/products"

  # Deploy API Gateway (Without StageName)
  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - AddProductMethod
      - GetProductsMethod
    Properties:
      RestApiId: !Ref APIGateway

  # Define API Gateway Stage (Separate from Deployment)
  APIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: "prod"
      RestApiId: !Ref APIGateway
      DeploymentId: !Ref APIDeployment
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath","status":"$context.status","responseLength":"$context.responseLength"}'
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: "INFO"
          DataTraceEnabled: true
          MetricsEnabled: true
