AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for MongoDB-backed API using Lambda and API Gateway with logging"

Parameters:
  MongoDBConnectionString:
    Type: String
    Description: "MongoDB Atlas Connection URI"

  LambdaS3Bucket:
    Type: String
    Description: "S3 Bucket where Lambda code is stored"

  LambdaS3Key:
    Type: String
    Description: "S3 Key for the Lambda function zip file"

Resources:

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: LambdaLoggingPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

  # CloudWatch Log Group for Lambda
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AddProductLambda}"
      RetentionInDays: 7  # Keep logs for 7 days

  # Lambda Function (S3-based)
  AddProductLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "AddProduct"
      Runtime: python3.8
      Handler: add_product.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
      Environment:
        Variables:
          MONGO_URI: !Ref MongoDBConnectionString
      Timeout: 10

  # API Gateway
  APIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "MongoDBProductAPI"

  # API Gateway CloudWatch Log Group
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/api-gateway/${APIGateway}"
      RetentionInDays: 7

  # API Resource (/products)
  ProductsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGateway
      ParentId: !GetAtt APIGateway.RootResourceId
      PathPart: "products"

  # API Method (POST /products/add)
  AddProductMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref APIGateway
      ResourceId: !Ref ProductsResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AddProductLambda.Arn}/invocations"
          - { AddProductLambda: !Ref AddProductLambda }

  # Deploy API Gateway with Logging Enabled
  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: AddProductMethod
    Properties:
      RestApiId: !Ref APIGateway
      StageName: "prod"
      StageDescription:
        AccessLogSetting:
          DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
          Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath","status":"$context.status","responseLength":"$context.responseLength"}'
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: "INFO"
          DataTraceEnabled: true
          MetricsEnabled: true

  # Grant API Gateway Permission to invoke Lambda
  AddProductLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AddProductLambda
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/*/POST/products/add"
