name: Deploy AWS Lambda & API Gateway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Dependencies & Package Lambda Functions
        run: |
          mkdir -p package
          pip install --target package -r lambda_functions/requirements.txt
          cp lambda_functions/*.py package/
          cd package
          zip -r ../add_product.zip .
          cd ..
          rm -rf package

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Upload Lambda ZIP to S3
        run: |
          aws s3 cp add_product.zip s3://${{ secrets.S3_BUCKET }}/add_product.zip

      - name: Export Environment Variables
        run: |
          echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> $GITHUB_ENV
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      - name: Debug Variables
        run: |
          echo "Using S3_BUCKET: $S3_BUCKET"
          echo "Using MONGO_URI: $MONGO_URI"

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name MongoDBProductAPI \
            --template-file cloudformation/serverless-api.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              MongoDBConnectionString=$MONGO_URI \
              LambdaS3Bucket=$S3_BUCKET \
              LambdaS3Key=add_product.zip
