name: Deploy AWS Lambda & API Gateway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Install Dependencies & Package Each Lambda Function
        run: |
          for dir in lambda_functions/*; do
            if [ -d "$dir" ]; then
              function_name=$(basename "$dir")
              echo "Packaging $function_name..."
              
              mkdir -p package
              pip install --target package -r "$dir/requirements.txt"
              cp "$dir"/*.py package/
              
              zip -r "${function_name}.zip" package/*
              aws s3 cp "${function_name}.zip" "s3://${{ secrets.S3_BUCKET }}/${function_name}.zip"

              rm -rf package "${function_name}.zip"
            fi
          done

      - name: Export Environment Variables
        run: |
          echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> $GITHUB_ENV
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      - name: Debug Variables
        run: |
          echo "Using S3_BUCKET: $S3_BUCKET"
          echo "Using MONGO_URI: $MONGO_URI"

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name MongoDBProductAPI \
            --template-file cloudformation/serverless-api.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              MongoDBConnectionString=$MONGO_URI \
              LambdaS3Bucket=$S3_BUCKET \
              LambdaS3Key=add_product.zip
